### PR TITLE
fix password validation

### PR DESCRIPTION
**Pull request by AntonioPavkovic**
added extra password validation
remove unused imports
https://github.com/Medic01/Sustav_za_transfuziologiju/issues/36

### CODE REVIEW

**Comment by jozogs** [comment]
@AntonioPavkovic please rebase and resolve conflicts

**Comment by jozogs** [comment]
@AntonioPavkovic this bug is still present...

**Comment by AntonioPavkovic** [comment]
> @AntonioPavkovic this bug is still present...

I have made changes. Take a look when you get a chance! :)

**Comment by AntonioPavkovic** [comment]
> > @AntonioPavkovic this bug is still present...
> 
> I have made changes. Take a look when you get a chance! :)

@jozogs

I have made changes and tested the registration page carefully. test and test123. don't pass but Test123. password passes and the user is successfully registered. When you get a chance take a look :)

**Review by jozogs — APPROVED** [review]

**Pull request merged**
